version: '3.7'
services:
  webpage:
    image: sboncio/app
    build: ./app
    command: gunicorn --workers=3 --bind 0.0.0.0:5000 app:app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - SQL_Password.env
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
    - target: 3306
      published: 3306
    
